apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tor.fullname" . }}-secret
  labels:
    {{- include "tor.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.env.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}