# Default values for tor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: barneybuffet/tor
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.4.6.7"

resources: 
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 32Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: 
  eks.amazonaws.com/nodegroup: public

tolerations:
- key: public
  value: "true"
  operator: "Equal"
  effect: "NoSchedule"

affinity: {}
