name: Docker Image build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN 
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 docker build . --tag deathmond1987/tor_for_r:latest
      
    - name: Docker Push
      run: docker push deathmond1987/tor_for_r:latest

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN 
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 docker build . --tag deathmond1987/tor_for_r:staging
      
    - name: Docker Push
      run: docker push deathmond1987/tor_for_r:staging
