name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build image
      run: DOCKER_BUILDKIT=1 docker build . --file Dockerfile --tag deathmond1987/tor_for_r:$(date +%s)
    
    - name: Login to DockerHub
    - uses: docker/login-action@v2
       with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Image digest
       run: echo ${{ steps.docker_build.outputs.digest }}
